language: 
  - python
python:
  - "3.6"
services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
install: 
  - cd src
  - pip install -r requirements.txt
before_script:   
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py migrate 
branches:
  only:
    - master
