language: 
  - python
python:
  - "3.6"
services: postgresql
install: 
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database postgres;' -U postgres
script:
  - python manage.py migrate 
  - python manage.py runserver
branches:
  only:
    - master