version: '3'

services:
  degree_planner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: degree_planner
    volumes:
      - ./degree_planner:/home/docker/degree_planner
    working_dir: /home/docker/degree_planner
    ports:
      - "8000:8000"
  db:
    image: postgres:9.4
    container_name: postgres_db
    volumes:
     - degree_planner_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: postgres_db
volumes:
  degree_planner_data:

